## Data Manipulation

In [8]:
from mxnet import nd

In [9]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [10]:
x.shape

(12,)

In [11]:
x.size

12

In [5]:
x.reshape((3, 4))
# could also use x.reshape((3, -1)) or x.reshape((-1, 4)) to infer the 2nd dimension



[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

create an empty array 
- be careful as it will be initialized with random variables that may already be in memory

In [12]:
nd.empty((3, 4))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

to create a tensor of dimension (2,3,4) with all zeros

In [14]:
nd.zeros((2, 3, 4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [15]:
# or ones
nd.ones((2, 3, 4))


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
<NDArray 2x3x4 @cpu(0)>

In [16]:
# can create an array by supplying python lists
nd.array([[5, 2, 1], [7, 9, 9], [4, 2, 1]])


[[5. 2. 1.]
 [7. 9. 9.]
 [4. 2. 1.]]
<NDArray 3x3 @cpu(0)>

In [17]:
# create an array by randomly sampling from a normal distribution
nd.random.normal(0, 1, shape=(3, 4))


[[-0.59164983  0.8586049  -0.22794184  0.20131476]
 [ 0.35005474  0.5360521   1.5194443   1.9040878 ]
 [-1.5734432  -0.14007865  0.29670078  1.3111951 ]]
<NDArray 3x4 @cpu(0)>

## Elementwise Operations

In [ ]:
x = nd.array([1, 2, 3, 4])
y = nd.ones_like(x) * 2
print('x = ', x)
print('x + y = ', x + y)
print('x - y = ', x - y)
print('x * y = ', x * y)
print('x / y = ', x / y)

x.exp()

## Matrix Operations

In [18]:
x = nd.arange(12).reshape((3, 4))
y = nd.array([[2, 1, 4, 5], [1, 2, 3, 4], [4, 3, 2, 1]])
nd.dot(x, y.T)


[[ 24.  20.  10.]
 [ 72.  60.  50.]
 [120. 100.  90.]]
<NDArray 3x3 @cpu(0)>