## Data Manipulation

In [1]:
from mxnet import nd

In [9]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [10]:
x.shape

(12,)

In [11]:
x.size

12

In [5]:
x.reshape((3, 4))
# could also use x.reshape((3, -1)) or x.reshape((-1, 4)) to infer the 2nd dimension



[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

create an empty array 
- be careful as it will be initialized with random variables that may already be in memory

In [12]:
nd.empty((3, 4))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

to create a tensor of dimension (2,3,4) with all zeros

In [14]:
nd.zeros((2, 3, 4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [15]:
# or ones
nd.ones((2, 3, 4))


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
<NDArray 2x3x4 @cpu(0)>

In [16]:
# can create an array by supplying python lists
nd.array([[5, 2, 1], [7, 9, 9], [4, 2, 1]])


[[5. 2. 1.]
 [7. 9. 9.]
 [4. 2. 1.]]
<NDArray 3x3 @cpu(0)>

In [17]:
# create an array by randomly sampling from a normal distribution
nd.random.normal(0, 1, shape=(3, 4))


[[-0.59164983  0.8586049  -0.22794184  0.20131476]
 [ 0.35005474  0.5360521   1.5194443   1.9040878 ]
 [-1.5734432  -0.14007865  0.29670078  1.3111951 ]]
<NDArray 3x4 @cpu(0)>

## Elementwise Operations

In [ ]:
x = nd.array([1, 2, 3, 4])
y = nd.ones_like(x) * 2
print('x = ', x)
print('x + y = ', x + y)
print('x - y = ', x - y)
print('x * y = ', x * y)
print('x / y = ', x / y)

x.exp()

## Matrix Operations

In [4]:
x = nd.arange(12).reshape((3, 4))
y = nd.array([[2, 1, 4, 5], [1, 2, 3, 4], [4, 3, 2, 1]])
nd.dot(x, y.T)


[[ 24.  20.  10.]
 [ 72.  60.  50.]
 [120. 100.  90.]]
<NDArray 3x3 @cpu(0)>

## Merging Matrices


In [5]:
# merge along rows
nd.concat(x, y, dim=0)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  5.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>

In [6]:
# merge along columns
nd.concat(x, y, dim=1)



[[ 0.  1.  2.  3.  2.  1.  4.  5.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>

## Other operations

In [ ]:
# turn into logical array
x == y


In [8]:
# sum all elements in an array
x.sum()


[66.]
<NDArray 1 @cpu(0)>

In [10]:
# transform from a single element ND array to a python scalar
x.norm().asscalar()



22.494442

## Broadcasting

In [3]:
# nd arrays handle adding different sized matrices by broadcasting them to a larger matrix
# (3x2 in this case) it will replicate matrix a's columns and matrix b's rows and then add elementwise 
a = nd.arange(3).reshape((3, 1))
b = nd.arange(2).reshape((1, 2))
a + b



[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

## Indexing and Slicing

In [6]:
# indexes from 0 and selects the first but not the last element, for example the below will
# select the 2nd and 3rd elements
print(x)
x[1:3]




[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>



[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [8]:
# Can write elements to the matrix
x[1, 2] = 9
x



[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [9]:
# can assign multiple values
x[0:2, :] = 12
x



[[12. 12. 12. 12.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

## Saving Memory
when running operations new memory is allocated to store the result, ie y = x + y allocates new memory to store the 
results


In [10]:
before = id(y)
y = y + x
after = id(y)
print(before)
print(after)


4755225120
4755018696


In [11]:
# To allocate memory in-place in mxnet you use the slice [:] notation, as show in example
z = y.zeros_like()
print('id(z)', id(z))
z[:] = x + y
print('id(z)', id(z))

# this still however uses a temporary buffer to store x + y

id(z) 4755018640
id(z) 4755018640


In [12]:
# to avoid using a temporary buffer you can envoke the underlying ndarray operation and by specifying the out keyword 
# argument, which every ndarray operation contains
print('id(z)', id(z))
nd.elemwise_add(x, y, out=z)
print('id(z)', id(z))

# you can also use += to reduce the overhead of memory operations, for example x += y as opposed to x = x + y

id(z) 4755018640
id(z) 4755018640


## Transfomation of NDArray and NumPy
Converted arrays do not share memory


In [13]:
import numpy as np
a = x.asnumpy()
print(type(a))
b = nd.array(a)
print(type(b))



<class 'numpy.ndarray'>
<class 'mxnet.ndarray.ndarray.NDArray'>
